#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNPOD_ENV_FILE_DEFAULT="${EDSVFH_RUNPOD_ENV_FILE:-${SCRIPT_DIR}/runpod.env}"
if [[ "${EDSVFH_AUTOLOAD_RUNPOD_ENV:-1}" == "1" ]] && [[ -f "${RUNPOD_ENV_FILE_DEFAULT}" ]] && [[ "${EDSVFH_RUNPOD_ENV_LOADED:-0}" != "1" ]]; then
  # shellcheck disable=SC1090
  source "${RUNPOD_ENV_FILE_DEFAULT}"
  export EDSVFH_RUNPOD_ENV_LOADED=1
fi
DEFAULT_PROJECT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
RESPECT_PROJECT_DIR_ENV="${EDSVFH_RESPECT_PROJECT_DIR_ENV:-0}"
if [[ "${RESPECT_PROJECT_DIR_ENV}" == "1" && -n "${PROJECT_DIR:-}" ]]; then
  PROJECT_DIR="${PROJECT_DIR}"
else
  PROJECT_DIR="${DEFAULT_PROJECT_DIR}"
fi
WORKSPACE_ROOT="${WORKSPACE_ROOT:-$(dirname "${PROJECT_DIR}")}"
DATA_ROOT="${DATA_ROOT:-${WORKSPACE_ROOT}/data}"
RAW_ROOT="${RAW_ROOT:-${DATA_ROOT}/raw}"
CONVERTED_ROOT="${CONVERTED_ROOT:-${DATA_ROOT}/converted}"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-${WORKSPACE_ROOT}/artifacts}"
LOG_ROOT="${LOG_ROOT:-${WORKSPACE_ROOT}/logs}"
CACHE_ROOT="${CACHE_ROOT:-${WORKSPACE_ROOT}/cache}"
CHECKPOINT_ROOT="${CHECKPOINT_ROOT:-${WORKSPACE_ROOT}/checkpoints}"

DROID_RAW_ROOT="${DROID_RAW_ROOT:-${RAW_ROOT}/droid}"
DROID_DEBUG_ROOT="${DROID_DEBUG_ROOT:-${CONVERTED_ROOT}/droid_debug}"
DROID_CURATED_ROOT="${DROID_CURATED_ROOT:-${CONVERTED_ROOT}/droid_curated}"
FINO_RAW_ROOT="${FINO_RAW_ROOT:-${RAW_ROOT}/fino}"
FINO_MANIFEST_PATH="${FINO_MANIFEST_PATH:-${FINO_RAW_ROOT}/fino_manifest.jsonl}"
FINO_PSEUDO_MANIFEST_PATH="${FINO_PSEUDO_MANIFEST_PATH:-${FINO_RAW_ROOT}/fino_manifest_pseudo_onset.jsonl}"
FINO_CONVERTED_ROOT="${FINO_CONVERTED_ROOT:-${CONVERTED_ROOT}/fino}"
DROID_BASELINE_SHARD_DIR="${DROID_BASELINE_SHARD_DIR:-${DROID_CURATED_ROOT}}"
DROID_SUCCESS_BASELINE_PATH="${DROID_SUCCESS_BASELINE_PATH:-${ARTIFACT_ROOT}/droid_success_baseline.pkl}"
BASE_BUNDLE="${BASE_BUNDLE:-${ARTIFACT_ROOT}/droid_curated_bundle.pkl}"
DROID_FAILURE_SOURCE_MODE="${DROID_FAILURE_SOURCE_MODE:-rlds}"
DROID_FAILURE_RLDS_ROOT="${DROID_FAILURE_RLDS_ROOT:-${DROID_SOURCE:-${DROID_RAW_ROOT}/1.0.1}}"
DROID_FAILURE_RLDS_SPLIT="${DROID_FAILURE_RLDS_SPLIT:-train}"
DROID_FAILURE_SCAN_MAX_EPISODES="${DROID_FAILURE_SCAN_MAX_EPISODES:-}"
DROID_FAILURE_RAW_ROOT="${DROID_FAILURE_RAW_ROOT:-${RAW_ROOT}/droid_raw/1.0.1}"
DROID_FAILURE_WORK_ROOT="${DROID_FAILURE_WORK_ROOT:-${RAW_ROOT}/droid_failure}"
DROID_FAILURE_FRAMES_ROOT="${DROID_FAILURE_FRAMES_ROOT:-${DROID_FAILURE_WORK_ROOT}/frames}"
DROID_FAILURE_MANIFEST_PATH="${DROID_FAILURE_MANIFEST_PATH:-${DROID_FAILURE_WORK_ROOT}/droid_failure_manifest.jsonl}"
DROID_FAILURE_PSEUDO_MANIFEST_PATH="${DROID_FAILURE_PSEUDO_MANIFEST_PATH:-${DROID_FAILURE_WORK_ROOT}/droid_failure_manifest_pseudo_onset.jsonl}"
DROID_FAILURE_CONVERTED_ROOT="${DROID_FAILURE_CONVERTED_ROOT:-${CONVERTED_ROOT}/droid_failure}"
DROID_FAILURE_BUNDLE="${DROID_FAILURE_BUNDLE:-${ARTIFACT_ROOT}/droid_droid_failure_bundle.pkl}"
DROID_FAILURE_MAX_EPISODES="${DROID_FAILURE_MAX_EPISODES:-}"
DROID_FAILURE_MAX_FRAMES_PER_EPISODE="${DROID_FAILURE_MAX_FRAMES_PER_EPISODE:-}"
DROID_FAILURE_FRAME_STRIDE="${DROID_FAILURE_FRAME_STRIDE:-${STEP_STRIDE:-2}}"
DROID_FAILURE_UPDATE_SCALER="${DROID_FAILURE_UPDATE_SCALER:-1}"
DROID_RAW_GCS_PREFIX="${DROID_RAW_GCS_PREFIX:-gs://gresearch/robotics/droid_raw/1.0.1}"
FINO_MANIFEST_CKPT="${FINO_MANIFEST_CKPT:-${CHECKPOINT_ROOT}/fino_manifest_ckpt.json}"
FINO_PSEUDO_CKPT="${FINO_PSEUDO_CKPT:-${CHECKPOINT_ROOT}/fino_pseudo_onset_ckpt.json}"
FINO_CONVERT_CKPT="${FINO_CONVERT_CKPT:-${CHECKPOINT_ROOT}/fino_convert_ckpt.json}"
DROID_FAILURE_PSEUDO_CKPT="${DROID_FAILURE_PSEUDO_CKPT:-${CHECKPOINT_ROOT}/droid_failure_pseudo_onset_ckpt.json}"
DROID_FAILURE_CONVERT_CKPT="${DROID_FAILURE_CONVERT_CKPT:-${CHECKPOINT_ROOT}/droid_failure_convert_ckpt.json}"
DROID_FAILURE_CKPT="${DROID_FAILURE_CKPT:-${CHECKPOINT_ROOT}/droid_failure_finetune_ckpt.pkl}"
DROID_FAILURE_MANIFEST_SCAN_CKPT="${DROID_FAILURE_MANIFEST_SCAN_CKPT:-${CHECKPOINT_ROOT}/droid_failure_manifest_scan_ckpt.json}"
DROID_FAILURE_MANIFEST_SCAN_CKPT_EVERY="${DROID_FAILURE_MANIFEST_SCAN_CKPT_EVERY:-64}"
DROID_FAILURE_MANIFEST_SCAN_RESUME="${DROID_FAILURE_MANIFEST_SCAN_RESUME:-1}"
EDSVFH_FORCE_RERUN="${EDSVFH_FORCE_RERUN:-0}"

DROID_DEBUG_CKPT="${DROID_DEBUG_CKPT:-${CHECKPOINT_ROOT}/droid_debug_train_ckpt.pkl}"
DROID_CURATED_CKPT="${DROID_CURATED_CKPT:-${CHECKPOINT_ROOT}/droid_curated_train_ckpt.pkl}"
FINO_CKPT="${FINO_CKPT:-${CHECKPOINT_ROOT}/fino_finetune_ckpt.pkl}"
CONVERT_DROID_CURATED_LOG="${CONVERT_DROID_CURATED_LOG:-${LOG_ROOT}/convert_droid_curated.log}"
TRAIN_DROID_CURATED_LOG="${TRAIN_DROID_CURATED_LOG:-${LOG_ROOT}/train_droid_curated.log}"
FINO_TRAIN_LOG="${FINO_TRAIN_LOG:-${LOG_ROOT}/fino_finetune.log}"
FINO_PSEUDO_PIPELINE_LOG="${FINO_PSEUDO_PIPELINE_LOG:-${LOG_ROOT}/fino_pseudo_onset_pipeline.log}"
FINO_MANIFEST_LOG="${FINO_MANIFEST_LOG:-${LOG_ROOT}/fino_manifest.log}"
DROID_SUCCESS_BASELINE_LOG="${DROID_SUCCESS_BASELINE_LOG:-${LOG_ROOT}/fit_droid_success_baseline.log}"
FINO_PSEUDO_LABEL_LOG="${FINO_PSEUDO_LABEL_LOG:-${LOG_ROOT}/label_fino_pseudo_onset.log}"
FINO_CONVERT_LOG="${FINO_CONVERT_LOG:-${LOG_ROOT}/convert_fino.log}"
DROID_FAILURE_MANIFEST_LOG="${DROID_FAILURE_MANIFEST_LOG:-${LOG_ROOT}/droid_failure_manifest.log}"
DROID_FAILURE_PSEUDO_LABEL_LOG="${DROID_FAILURE_PSEUDO_LABEL_LOG:-${LOG_ROOT}/label_droid_failure_pseudo_onset.log}"
DROID_FAILURE_CONVERT_LOG="${DROID_FAILURE_CONVERT_LOG:-${LOG_ROOT}/convert_droid_failure.log}"
DROID_FAILURE_TRAIN_LOG="${DROID_FAILURE_TRAIN_LOG:-${LOG_ROOT}/droid_failure_finetune.log}"
DROID_FAILURE_PSEUDO_PIPELINE_LOG="${DROID_FAILURE_PSEUDO_PIPELINE_LOG:-${LOG_ROOT}/droid_failure_pseudo_onset_pipeline.log}"
BG_STATE_ROOT="${BG_STATE_ROOT:-${LOG_ROOT}/bg_state}"
PAPER_PACK_OUTPUT_ROOT="${PAPER_PACK_OUTPUT_ROOT:-${WORKSPACE_ROOT}}"
PAPER_PACK_PREFIX="${PAPER_PACK_PREFIX:-paper_pack}"
PAPER_PACK_LOG="${PAPER_PACK_LOG:-${LOG_ROOT}/paper_pack_results.log}"
PAPER_PACK_INCLUDE_FULL="${PAPER_PACK_INCLUDE_FULL:-1}"
PAPER_PACK_INCLUDE_RAW_ENV="${PAPER_PACK_INCLUDE_RAW_ENV:-0}"
PAPER_PACK_SKIP_EVAL="${PAPER_PACK_SKIP_EVAL:-0}"
PAPER_PACK_HEAD_LINES="${PAPER_PACK_HEAD_LINES:-20}"
PAPER_PACK_TOPK_CHANGED="${PAPER_PACK_TOPK_CHANGED:-30}"

ENCODER="${ENCODER:-fallback}"
MAX_EPISODES="${MAX_EPISODES:-}"
IMAGE_SIZE="${IMAGE_SIZE:-96}"
EPISODES_PER_SHARD="${EPISODES_PER_SHARD:-64}"
STEP_STRIDE="${STEP_STRIDE:-2}"
ACTION_SPACE="${ACTION_SPACE:-raw_action}"
USE_HF="${USE_HF:-0}"
EDSVFH_HF_LOCAL_ONLY="${EDSVFH_HF_LOCAL_ONLY:-0}"
USE_PSEUDO_ONSET="${USE_PSEUDO_ONSET:-1}"
EPOCHS="${EPOCHS:-3}"
CONVERT_BATCH_SIZE="${CONVERT_BATCH_SIZE:-16}"
EDSVFH_DISABLE_CUDNN="${EDSVFH_DISABLE_CUDNN:-0}"
PSEUDO_ONSET_FEATURE_SOURCE="${PSEUDO_ONSET_FEATURE_SOURCE:-visual}"
PSEUDO_ONSET_WINDOW="${PSEUDO_ONSET_WINDOW:-3}"
PSEUDO_ONSET_PHASE_BINS="${PSEUDO_ONSET_PHASE_BINS:-10}"
PSEUDO_ONSET_QUANTILE="${PSEUDO_ONSET_QUANTILE:-0.97}"
PSEUDO_ONSET_MIN_PHASE_COUNT="${PSEUDO_ONSET_MIN_PHASE_COUNT:-8}"
PSEUDO_ONSET_FIT_MAX_EPISODES="${PSEUDO_ONSET_FIT_MAX_EPISODES:-}"
FINO_UPDATE_SCALER="${FINO_UPDATE_SCALER:-1}"
HORIZONS="${HORIZONS:-1,3,5}"
export EDSVFH_HORIZONS="${EDSVFH_HORIZONS:-${HORIZONS}}"
LARGER_HORIZONS="${LARGER_HORIZONS:-1,3,5,10,15}"
LARGER_HORIZONS_EPOCHS="${LARGER_HORIZONS_EPOCHS:-${EPOCHS}}"
LARGER_HORIZONS_BASE_BUNDLE="${LARGER_HORIZONS_BASE_BUNDLE:-${DROID_FAILURE_BUNDLE}}"
LARGER_HORIZONS_FREEZE_EXISTING="${LARGER_HORIZONS_FREEZE_EXISTING:-1}"
LARGER_HORIZONS_UPDATE_SCALER="${LARGER_HORIZONS_UPDATE_SCALER:-0}"
LARGER_HORIZONS_RESUME="${LARGER_HORIZONS_RESUME:-0}"
LARGER_HORIZONS_SLUG="${LARGER_HORIZONS//,/x}"
LARGER_HORIZONS_OUTPUT_BUNDLE="${LARGER_HORIZONS_OUTPUT_BUNDLE:-${ARTIFACT_ROOT}/droid_droid_failure_bundle_horizons_${LARGER_HORIZONS_SLUG}.pkl}"
LARGER_HORIZONS_CKPT="${LARGER_HORIZONS_CKPT:-${CHECKPOINT_ROOT}/droid_failure_larger_horizons_${LARGER_HORIZONS_SLUG}_ckpt.pkl}"
LARGER_HORIZONS_LOG="${LARGER_HORIZONS_LOG:-${LOG_ROOT}/test_droid_failure_larger_horizons_${LARGER_HORIZONS_SLUG}.log}"
export DROID_FAILURE_SOURCE_MODE DROID_FAILURE_RLDS_ROOT DROID_FAILURE_RLDS_SPLIT DROID_FAILURE_SCAN_MAX_EPISODES DROID_FAILURE_RAW_ROOT DROID_FAILURE_WORK_ROOT DROID_FAILURE_FRAMES_ROOT DROID_FAILURE_MANIFEST_PATH DROID_FAILURE_PSEUDO_MANIFEST_PATH DROID_FAILURE_CONVERTED_ROOT DROID_FAILURE_BUNDLE DROID_FAILURE_MAX_EPISODES DROID_FAILURE_MAX_FRAMES_PER_EPISODE DROID_FAILURE_FRAME_STRIDE DROID_FAILURE_UPDATE_SCALER DROID_RAW_GCS_PREFIX DROID_FAILURE_MANIFEST_LOG DROID_FAILURE_PSEUDO_LABEL_LOG DROID_FAILURE_CONVERT_LOG DROID_FAILURE_TRAIN_LOG DROID_FAILURE_PSEUDO_PIPELINE_LOG DROID_FAILURE_PSEUDO_CKPT DROID_FAILURE_CONVERT_CKPT DROID_FAILURE_CKPT DROID_FAILURE_MANIFEST_SCAN_CKPT DROID_FAILURE_MANIFEST_SCAN_CKPT_EVERY DROID_FAILURE_MANIFEST_SCAN_RESUME EDSVFH_FORCE_RERUN
export HORIZONS EDSVFH_HORIZONS LARGER_HORIZONS LARGER_HORIZONS_BASE_BUNDLE LARGER_HORIZONS_FREEZE_EXISTING LARGER_HORIZONS_EPOCHS LARGER_HORIZONS_UPDATE_SCALER LARGER_HORIZONS_RESUME LARGER_HORIZONS_OUTPUT_BUNDLE LARGER_HORIZONS_CKPT LARGER_HORIZONS_LOG
CANARY_PSEUDO_ONSET_FIT_MAX_EPISODES="${CANARY_PSEUDO_ONSET_FIT_MAX_EPISODES:-256}"
CANARY_EPOCHS="${CANARY_EPOCHS:-1}"
CANARY_RUN_TARGETED_TESTS="${CANARY_RUN_TARGETED_TESTS:-1}"
CANARY_RUN_PIPELINE="${CANARY_RUN_PIPELINE:-1}"
CANARY_STRICT="${CANARY_STRICT:-1}"
CANARY_LOG="${CANARY_LOG:-${LOG_ROOT}/validate_clean_rerun_canary.log}"
CANARY_SUMMARY_JSON="${CANARY_SUMMARY_JSON:-${LOG_ROOT}/clean_rerun_canary_summary.json}"
CANARY_SUMMARY_TXT="${CANARY_SUMMARY_TXT:-${LOG_ROOT}/clean_rerun_canary_summary.txt}"

REPLAY_BUNDLE="${REPLAY_BUNDLE:-${LARGER_HORIZONS_OUTPUT_BUNDLE}}"
REPLAY_FIXED_RATES="${REPLAY_FIXED_RATES:-1,3,5,10,15,30,45,60}"
REPLAY_ALARM_DECISIONS="${REPLAY_ALARM_DECISIONS:-watch,shield,abstain}"
REPLAY_STOP_ON_TERMINAL="${REPLAY_STOP_ON_TERMINAL:-1}"
REPLAY_MAX_EPISODES="${REPLAY_MAX_EPISODES:-}"
REPLAY_OUTPUT_JSON="${REPLAY_OUTPUT_JSON:-${LOG_ROOT}/replay_protocol_metrics.json}"
REPLAY_OUTPUT_CSV="${REPLAY_OUTPUT_CSV:-${LOG_ROOT}/replay_protocol_metrics.csv}"
REPLAY_LOG="${REPLAY_LOG:-${LOG_ROOT}/replay_protocol_eval.log}"

ABLATION_BUNDLES="${ABLATION_BUNDLES:-main=${DROID_FAILURE_BUNDLE},extended=${LARGER_HORIZONS_OUTPUT_BUNDLE}}"
ABLATION_VARIANTS="${ABLATION_VARIANTS:-calibrated_monotonic,calibrated,raw_monotonic,raw}"
ABLATION_ECE_BINS="${ABLATION_ECE_BINS:-10}"
ABLATION_OUTPUT_JSON="${ABLATION_OUTPUT_JSON:-${LOG_ROOT}/ablation_suite_metrics.json}"
ABLATION_OUTPUT_CSV="${ABLATION_OUTPUT_CSV:-${LOG_ROOT}/ablation_suite_metrics.csv}"
ABLATION_LOG="${ABLATION_LOG:-${LOG_ROOT}/ablation_suite_eval.log}"
export REPLAY_BUNDLE REPLAY_FIXED_RATES REPLAY_ALARM_DECISIONS REPLAY_STOP_ON_TERMINAL REPLAY_MAX_EPISODES REPLAY_OUTPUT_JSON REPLAY_OUTPUT_CSV REPLAY_LOG
export ABLATION_BUNDLES ABLATION_VARIANTS ABLATION_ECE_BINS ABLATION_OUTPUT_JSON ABLATION_OUTPUT_CSV ABLATION_LOG
export EDSVFH_HF_LOCAL_ONLY
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
if [[ -n "${PYTHONPATH:-}" ]]; then
  case ":${PYTHONPATH}:" in
    *":${PROJECT_DIR}:"*) ;;
    *) export PYTHONPATH="${PROJECT_DIR}:${PYTHONPATH}" ;;
  esac
else
  export PYTHONPATH="${PROJECT_DIR}"
fi
if [[ "${USE_HF}" == "1" && "${ENCODER}" == "fallback" ]]; then
  ENCODER="siglip2_dinov2"
fi


ensure_dirs() {
  mkdir -p "${PROJECT_DIR}" \
           "${RAW_ROOT}" \
           "${CONVERTED_ROOT}" \
           "${ARTIFACT_ROOT}" \
           "${LOG_ROOT}" \
           "${CACHE_ROOT}" \
           "${CHECKPOINT_ROOT}" \
           "${BG_STATE_ROOT}" \
           "${PAPER_PACK_OUTPUT_ROOT}" \
           "${DROID_RAW_ROOT}" \
           "${DROID_DEBUG_ROOT}" \
           "${DROID_CURATED_ROOT}" \
           "${DROID_FAILURE_RAW_ROOT}" \
           "${DROID_FAILURE_WORK_ROOT}" \
           "${DROID_FAILURE_FRAMES_ROOT}" \
           "${DROID_FAILURE_CONVERTED_ROOT}" \
           "${FINO_RAW_ROOT}" \
           "${FINO_CONVERTED_ROOT}"
}

print_layout() {
  cat <<LAYOUT
WORKSPACE_ROOT=${WORKSPACE_ROOT}
PROJECT_DIR=${PROJECT_DIR}
DATA_ROOT=${DATA_ROOT}
RAW_ROOT=${RAW_ROOT}
CONVERTED_ROOT=${CONVERTED_ROOT}
ARTIFACT_ROOT=${ARTIFACT_ROOT}
LOG_ROOT=${LOG_ROOT}
CACHE_ROOT=${CACHE_ROOT}
DROID_RAW_ROOT=${DROID_RAW_ROOT}
DROID_DEBUG_ROOT=${DROID_DEBUG_ROOT}
DROID_CURATED_ROOT=${DROID_CURATED_ROOT}
FINO_RAW_ROOT=${FINO_RAW_ROOT}
FINO_MANIFEST_PATH=${FINO_MANIFEST_PATH}
FINO_PSEUDO_MANIFEST_PATH=${FINO_PSEUDO_MANIFEST_PATH}
FINO_CONVERTED_ROOT=${FINO_CONVERTED_ROOT}
DROID_BASELINE_SHARD_DIR=${DROID_BASELINE_SHARD_DIR}
DROID_SUCCESS_BASELINE_PATH=${DROID_SUCCESS_BASELINE_PATH}
BASE_BUNDLE=${BASE_BUNDLE}
DROID_FAILURE_SOURCE_MODE=${DROID_FAILURE_SOURCE_MODE}
DROID_FAILURE_RLDS_ROOT=${DROID_FAILURE_RLDS_ROOT}
DROID_FAILURE_RLDS_SPLIT=${DROID_FAILURE_RLDS_SPLIT}
DROID_FAILURE_SCAN_MAX_EPISODES=${DROID_FAILURE_SCAN_MAX_EPISODES}
DROID_FAILURE_RAW_ROOT=${DROID_FAILURE_RAW_ROOT}
DROID_FAILURE_WORK_ROOT=${DROID_FAILURE_WORK_ROOT}
DROID_FAILURE_FRAMES_ROOT=${DROID_FAILURE_FRAMES_ROOT}
DROID_FAILURE_MANIFEST_PATH=${DROID_FAILURE_MANIFEST_PATH}
DROID_FAILURE_PSEUDO_MANIFEST_PATH=${DROID_FAILURE_PSEUDO_MANIFEST_PATH}
DROID_FAILURE_CONVERTED_ROOT=${DROID_FAILURE_CONVERTED_ROOT}
DROID_FAILURE_BUNDLE=${DROID_FAILURE_BUNDLE}
DROID_FAILURE_MAX_EPISODES=${DROID_FAILURE_MAX_EPISODES}
DROID_FAILURE_MAX_FRAMES_PER_EPISODE=${DROID_FAILURE_MAX_FRAMES_PER_EPISODE}
DROID_FAILURE_FRAME_STRIDE=${DROID_FAILURE_FRAME_STRIDE}
DROID_FAILURE_UPDATE_SCALER=${DROID_FAILURE_UPDATE_SCALER}
FINO_MANIFEST_CKPT=${FINO_MANIFEST_CKPT}
FINO_PSEUDO_CKPT=${FINO_PSEUDO_CKPT}
FINO_CONVERT_CKPT=${FINO_CONVERT_CKPT}
CHECKPOINT_ROOT=${CHECKPOINT_ROOT}
DROID_DEBUG_CKPT=${DROID_DEBUG_CKPT}
DROID_CURATED_CKPT=${DROID_CURATED_CKPT}
FINO_CKPT=${FINO_CKPT}
CONVERT_DROID_CURATED_LOG=${CONVERT_DROID_CURATED_LOG}
TRAIN_DROID_CURATED_LOG=${TRAIN_DROID_CURATED_LOG}
FINO_TRAIN_LOG=${FINO_TRAIN_LOG}
FINO_PSEUDO_PIPELINE_LOG=${FINO_PSEUDO_PIPELINE_LOG}
FINO_MANIFEST_LOG=${FINO_MANIFEST_LOG}
DROID_SUCCESS_BASELINE_LOG=${DROID_SUCCESS_BASELINE_LOG}
FINO_PSEUDO_LABEL_LOG=${FINO_PSEUDO_LABEL_LOG}
FINO_CONVERT_LOG=${FINO_CONVERT_LOG}
DROID_FAILURE_MANIFEST_LOG=${DROID_FAILURE_MANIFEST_LOG}
DROID_FAILURE_PSEUDO_LABEL_LOG=${DROID_FAILURE_PSEUDO_LABEL_LOG}
DROID_FAILURE_CONVERT_LOG=${DROID_FAILURE_CONVERT_LOG}
DROID_FAILURE_TRAIN_LOG=${DROID_FAILURE_TRAIN_LOG}
DROID_FAILURE_PSEUDO_PIPELINE_LOG=${DROID_FAILURE_PSEUDO_PIPELINE_LOG}
DROID_FAILURE_PSEUDO_CKPT=${DROID_FAILURE_PSEUDO_CKPT}
DROID_FAILURE_CONVERT_CKPT=${DROID_FAILURE_CONVERT_CKPT}
DROID_FAILURE_CKPT=${DROID_FAILURE_CKPT}
DROID_FAILURE_MANIFEST_SCAN_CKPT=${DROID_FAILURE_MANIFEST_SCAN_CKPT}
DROID_FAILURE_MANIFEST_SCAN_CKPT_EVERY=${DROID_FAILURE_MANIFEST_SCAN_CKPT_EVERY}
DROID_FAILURE_MANIFEST_SCAN_RESUME=${DROID_FAILURE_MANIFEST_SCAN_RESUME}
EDSVFH_FORCE_RERUN=${EDSVFH_FORCE_RERUN}
BG_STATE_ROOT=${BG_STATE_ROOT}
PAPER_PACK_OUTPUT_ROOT=${PAPER_PACK_OUTPUT_ROOT}
PAPER_PACK_PREFIX=${PAPER_PACK_PREFIX}
PAPER_PACK_LOG=${PAPER_PACK_LOG}
PAPER_PACK_INCLUDE_FULL=${PAPER_PACK_INCLUDE_FULL}
PAPER_PACK_INCLUDE_RAW_ENV=${PAPER_PACK_INCLUDE_RAW_ENV}
PAPER_PACK_SKIP_EVAL=${PAPER_PACK_SKIP_EVAL}
PAPER_PACK_HEAD_LINES=${PAPER_PACK_HEAD_LINES}
PAPER_PACK_TOPK_CHANGED=${PAPER_PACK_TOPK_CHANGED}
ENCODER=${ENCODER}
MAX_EPISODES=${MAX_EPISODES}
IMAGE_SIZE=${IMAGE_SIZE}
EPISODES_PER_SHARD=${EPISODES_PER_SHARD}
STEP_STRIDE=${STEP_STRIDE}
ACTION_SPACE=${ACTION_SPACE}
USE_HF=${USE_HF}
USE_PSEUDO_ONSET=${USE_PSEUDO_ONSET}
EPOCHS=${EPOCHS}
CONVERT_BATCH_SIZE=${CONVERT_BATCH_SIZE}
EDSVFH_DISABLE_CUDNN=${EDSVFH_DISABLE_CUDNN}
PSEUDO_ONSET_FEATURE_SOURCE=${PSEUDO_ONSET_FEATURE_SOURCE}
PSEUDO_ONSET_WINDOW=${PSEUDO_ONSET_WINDOW}
PSEUDO_ONSET_PHASE_BINS=${PSEUDO_ONSET_PHASE_BINS}
PSEUDO_ONSET_QUANTILE=${PSEUDO_ONSET_QUANTILE}
PSEUDO_ONSET_MIN_PHASE_COUNT=${PSEUDO_ONSET_MIN_PHASE_COUNT}
PSEUDO_ONSET_FIT_MAX_EPISODES=${PSEUDO_ONSET_FIT_MAX_EPISODES}
FINO_UPDATE_SCALER=${FINO_UPDATE_SCALER}
HORIZONS=${HORIZONS}
EDSVFH_HORIZONS=${EDSVFH_HORIZONS}
LARGER_HORIZONS=${LARGER_HORIZONS}
LARGER_HORIZONS_BASE_BUNDLE=${LARGER_HORIZONS_BASE_BUNDLE}
LARGER_HORIZONS_FREEZE_EXISTING=${LARGER_HORIZONS_FREEZE_EXISTING}
LARGER_HORIZONS_EPOCHS=${LARGER_HORIZONS_EPOCHS}
LARGER_HORIZONS_UPDATE_SCALER=${LARGER_HORIZONS_UPDATE_SCALER}
LARGER_HORIZONS_RESUME=${LARGER_HORIZONS_RESUME}
LARGER_HORIZONS_OUTPUT_BUNDLE=${LARGER_HORIZONS_OUTPUT_BUNDLE}
LARGER_HORIZONS_CKPT=${LARGER_HORIZONS_CKPT}
LARGER_HORIZONS_LOG=${LARGER_HORIZONS_LOG}
CANARY_PSEUDO_ONSET_FIT_MAX_EPISODES=${CANARY_PSEUDO_ONSET_FIT_MAX_EPISODES}
CANARY_EPOCHS=${CANARY_EPOCHS}
CANARY_RUN_TARGETED_TESTS=${CANARY_RUN_TARGETED_TESTS}
CANARY_RUN_PIPELINE=${CANARY_RUN_PIPELINE}
CANARY_STRICT=${CANARY_STRICT}
CANARY_LOG=${CANARY_LOG}
CANARY_SUMMARY_JSON=${CANARY_SUMMARY_JSON}
CANARY_SUMMARY_TXT=${CANARY_SUMMARY_TXT}
REPLAY_BUNDLE=${REPLAY_BUNDLE}
REPLAY_FIXED_RATES=${REPLAY_FIXED_RATES}
REPLAY_ALARM_DECISIONS=${REPLAY_ALARM_DECISIONS}
REPLAY_STOP_ON_TERMINAL=${REPLAY_STOP_ON_TERMINAL}
REPLAY_MAX_EPISODES=${REPLAY_MAX_EPISODES}
REPLAY_OUTPUT_JSON=${REPLAY_OUTPUT_JSON}
REPLAY_OUTPUT_CSV=${REPLAY_OUTPUT_CSV}
REPLAY_LOG=${REPLAY_LOG}
ABLATION_BUNDLES=${ABLATION_BUNDLES}
ABLATION_VARIANTS=${ABLATION_VARIANTS}
ABLATION_ECE_BINS=${ABLATION_ECE_BINS}
ABLATION_OUTPUT_JSON=${ABLATION_OUTPUT_JSON}
ABLATION_OUTPUT_CSV=${ABLATION_OUTPUT_CSV}
ABLATION_LOG=${ABLATION_LOG}
LAYOUT
}

log_step() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

format_seconds() {
  local total=${1:-0}
  local h=$(( total / 3600 ))
  local m=$(( (total % 3600) / 60 ))
  local s=$(( total % 60 ))
  if (( h > 0 )); then
    printf '%02d:%02d:%02d' "$h" "$m" "$s"
  else
    printf '%02d:%02d' "$m" "$s"
  fi
}

run_timed() {
  local label="$1"
  shift
  log_step "START ${label}"
  local start_ts=$(date +%s)
  "$@"
  local rc=$?
  local end_ts=$(date +%s)
  local elapsed=$(( end_ts - start_ts ))
  log_step "END   ${label} | elapsed $(format_seconds ${elapsed}) | exit=${rc}"
  return ${rc}
}

_format_cmd_quoted() {
  local out=""
  local token
  for token in "$@"; do
    out+="$(printf '%q' "${token}") "
  done
  printf '%s' "${out% }"
}

_spawn_detached() {
  local log_path="$1"
  shift
  if command -v setsid >/dev/null 2>&1; then
    setsid nohup "$@" >> "${log_path}" 2>&1 < /dev/null &
  else
    nohup "$@" >> "${log_path}" 2>&1 < /dev/null &
  fi
  echo "$!"
}

launch_bg() {
  local log_path="$1"
  shift
  mkdir -p "$(dirname "${log_path}")"
  _spawn_detached "${log_path}" "$@"
}

launch_bg_named() {
  local name="$1"
  local log_path="$2"
  shift 2
  mkdir -p "$(dirname "${log_path}")" "${BG_STATE_ROOT}"
  local pid_file="${BG_STATE_ROOT}/${name}.pid"
  local meta_file="${BG_STATE_ROOT}/${name}.meta"
  local cmd_string
  cmd_string="$(_format_cmd_quoted "$@")"
  {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] START background ${name}"
    echo "PROJECT_DIR=${PROJECT_DIR}"
    echo "WORKSPACE_ROOT=${WORKSPACE_ROOT}"
    echo "CMD=${cmd_string}"
  } >> "${log_path}"
  local pid
  pid="$(_spawn_detached "${log_path}" "$@")"
  printf '%s\n' "${pid}" > "${pid_file}"
  {
    echo "name=${name}"
    echo "pid=${pid}"
    echo "log=${log_path}"
    echo "started_at=$(date -Is)"
    echo "cmd=${cmd_string}"
  } > "${meta_file}"
  echo "${pid}"
}

bg_pid_files() {
  if [[ -d "${BG_STATE_ROOT}" ]]; then
    find "${BG_STATE_ROOT}" -maxdepth 1 -type f -name '*.pid' | sort
  fi
}



dir_has_hdf5() {
  local path="$1"
  [[ -d "${path}" ]] && find "${path}" -type f \( -name '*.hdf5' -o -name '*.h5' \) -print -quit 2>/dev/null | grep -q .
}

should_force_rerun() {
  [[ "${EDSVFH_FORCE_RERUN:-0}" == "1" ]]
}

show_named_bg_status() {
  local pid_file="$1"
  local name="$(basename "${pid_file}" .pid)"
  local pid=""
  if [[ -f "${pid_file}" ]]; then
    pid="$(<"${pid_file}")"
  fi
  local meta_file="${BG_STATE_ROOT}/${name}.meta"
  local log_path=""
  if [[ -f "${meta_file}" ]]; then
    log_path="$(grep -E '^log=' "${meta_file}" | head -n1 | cut -d= -f2-)"
  fi
  echo "### ${name}"
  if [[ -n "${pid}" ]] && ps -p "${pid}" > /dev/null 2>&1; then
    ps -p "${pid}" -o pid,etime,cmd
  else
    echo "status=not_running pid=${pid:-unknown}"
  fi
  if [[ -n "${log_path}" ]]; then
    echo "log=${log_path}"
  fi
}

resolve_droid_baseline_shard_dir() {
  local candidate="${DROID_BASELINE_SHARD_DIR:-${DROID_CURATED_ROOT}}"
  if [[ -d "${candidate}" ]] && find "${candidate}" -type f \( -name '*.hdf5' -o -name '*.h5' \) -print -quit 2>/dev/null | grep -q .; then
    printf '%s\n' "${candidate}"
    return 0
  fi
  candidate="${DROID_DEBUG_ROOT}"
  if [[ -d "${candidate}" ]] && find "${candidate}" -type f \( -name '*.hdf5' -o -name '*.h5' \) -print -quit 2>/dev/null | grep -q .; then
    printf '%s\n' "${candidate}"
    return 0
  fi
  return 1
}

resolve_base_bundle_path() {
  local candidate="${BASE_BUNDLE:-${ARTIFACT_ROOT}/droid_curated_bundle.pkl}"
  if [[ -f "${candidate}" ]]; then
    printf '%s\n' "${candidate}"
    return 0
  fi
  candidate="${ARTIFACT_ROOT}/droid_curated_bundle.pkl"
  if [[ -f "${candidate}" ]]; then
    printf '%s\n' "${candidate}"
    return 0
  fi
  candidate="${ARTIFACT_ROOT}/droid_debug_bundle.pkl"
  if [[ -f "${candidate}" ]]; then
    printf '%s\n' "${candidate}"
    return 0
  fi
  return 1
}

show_pid_status() {
  local pid="$1"
  ps -p "${pid}" -o pid,etime,cmd
}
